### PR TITLE
Mediation by Mediator Coordination Protocol

### PR DESCRIPTION
**Pull request by genaris**
Implementation of routing through Aries RFC 0211 messages (Mediation Request, Mediation Grant and Mediation Deny) for both mediator and recipient role.

This approach is functionally equivalent to current provisioning feature, but does dynamically assign agent's Incoming Connection to allow a new agent to start immediately working as soon as it gets a Mediation Grant message from the mediator. However, it is not as 'automatic' as the other one, because the controller application decides either mediations are granted or denied (mediator role) and set as default incoming connection (recipient role), much in the same way as implemented in ACA-Py.

Mediation flows are recorded in the wallet so they can be tracked and also restored in further sessions: if **mediatorRecordId** is specified in AgentConfig, it is automatically set as the inbound connection.

Even if this implementation is quite primitive and does not completely support RFC 0211 protocol, this PR could solve (at least partially) some mediation-related issues such as #203, #230 and #63.

### CODE REVIEW

**Comment by TimoGlastra** [comment]
Awesome! 

I know @JamesKEbert was also working on this. Are you working together on this, or is this a separate implementation?

**Comment by genaris** [comment]
> Awesome!
> 
> I know @JamesKEbert was also working on this. Are you working together on this, or is this a separate implementation?

Oops, I've just seen that in the comments of #203 :-( I don't know if his implementation is in progress, but hopefully we can join efforts to bring AFJ full support for mediation protocol!

**Comment by TimoGlastra** [comment]
I hope so as well! Seems like you've put quite some work in this.

@JamesKEbert I'm not sure what the best approach is here. Could you take a look and see what's possible?

**Comment by burdettadam** [comment]
@genaris great contributions! I am helping @JamesKEbert and @DavidClawson with using aca-py as a mediator. We have a lot of overlapping code. I propose we make a new branch for mediation development and merge this pr there, then we can merge our efforts into that branch. We can then more casually share coding efforts.

**Comment by JamesKEbert** [comment]
Thank you for your efforts here @genaris! I second @burdettadam's proposal to create a branch for mediation or a develop/ branch. We've been moving a little slower on this than I would have liked due to business obligations, but have been making decent headway. 
I think that creating a separate branch could potentially give us a place to compile the efforts and reduce duplication of work. 

@genaris, do you plan on attending the Aries Framework Javacript community calls? It could be a helpful place to coordinate efforts?

**Comment by genaris** [comment]
Thanks for the comments, guys! It's a shame I haven't seen your mediation branches before, but anyway it's good that we are mostly in the same direction.

@burdettadam I agree! It seems that our approaches are quite compatible: I just didn't remove provisioning stuff to not break things. However, I definitely think this mediation module shall replace it.

@JamesKEbert Sure! I'll do my best to join you in the next community calls so we can follow this up.

**Comment by TimoGlastra** [comment]
OK -- I created a new branch you can work on together. 

https://github.com/hyperledger/aries-framework-javascript/tree/feature/mediation

@genaris If you can point you PR to this new branch I'll make sure to get it merged and we can go from there

**Comment by TimoGlastra** [comment]
Also, @jakubkoci are you fine with @JamesKEbert becoming maintainer? Then he can coordinate the work and have the permission to do that.

I think it would be good to have more maintainers anyway

**Review by TimoGlastra — APPROVED** [review]

**Comment by TimoGlastra** [comment]
BTW @genaris could you first fix the DCO issues? This will be a tedious thing to fix later on. 

See https://github.com/hyperledger/aries-rfcs/blob/master/contributing.md#how-to-sign-off-previous-commits

**Comment by genaris** [comment]
> BTW @genaris could you first fix the DCO issues? This will be a tedious thing to fix later on.
> 
> See https://github.com/hyperledger/aries-rfcs/blob/master/contributing.md#how-to-sign-off-previous-commits

@TimoGlastra, I've had a hard time doing so but I hope it is fine now. Please let me know if if is OK!

**Comment by genaris** [comment]
I think the merge that was in-between some of my commits messed everything up while trying to sign them off :-(

Maybe I can fork main's current status on another branch and then put everything in a single commit for a new PR?

**Comment by TimoGlastra** [comment]
> I think the merge that was in-between some of my commits messed everything up while trying to sign them off :-(
> 
> Maybe I can fork main's current status on another branch and then put everything in a single commit for a new PR?

Sounds good!

**Comment by genaris** [comment]
OK, I created #252 to follow this up. I think this one can be closed.

**Comment by JamesKEbert** [comment]
> Also, @jakubkoci are you fine with @JamesKEbert becoming maintainer? Then he can coordinate the work and have the permission to do that.

Would definitely be interested in becoming a maintainer. Would love to be able to continue helping push AFJ forward!

**Comment by jakubkoci** [comment]
> > Also, @jakubkoci are you fine with @JamesKEbert becoming maintainer? Then he can coordinate the work and have the permission to do that.
> 
> Would definitely be interested in becoming a maintainer. Would love to be able to continue helping push AFJ forward!

Yes. No problem with that 😎 However, I'm not a maintainer of maintainers :) Perhaps @matt-raffel-kiva could help with that. Matt, could you please add @JamesKEbert as a member in https://github.com/orgs/hyperledger/teams/aries-framework-javascript-committers? And maybe assign the maintainer role to at least one of the rest of us?

**Pull request closed without merging**
