### PR TITLE
fix: Use custom make-error with cause that works in RN

### PR DESCRIPTION
**Pull request by jakubkoci**
I forked [make-error-cause](https://github.com/blakeembrey/make-error-cause) and replaced Node.js `inspect` dependency with [util-inspect](https://github.com/Automattic/util-inspect). I'm not saying this is the final solution but it should make it work at least for now (I tested it with RN).

The issue describing the problem is #281.

### CODE REVIEW

**Comment by TimoGlastra** [comment]
The library is one file. Can't we just copy it into the framework?

**Comment by TimoGlastra** [comment]
It's apache. So if we add a copyright notice of the original author we're fine

**Comment by jakubkoci** [comment]
> `util-inspect` doesn't have a license which means we legally can't use it.
> 
> https://choosealicense.com/no-permission/
> https://github.com/Automattic/util-inspect

🤦‍♂️ 😄 

I found a different module [object-inspect](https://www.npmjs.com/package/object-inspect), works in React Native, MIT license.

I realize that the `inspect` method is actually used only when you specifically call `error.inspect()` and it doesn't provide any benefits in common scenarios.

**Review by TimoGlastra — APPROVED** [review]
Nice! A lot less dependencies also

**Pull request merged**
