### PR TITLE
fix(indy): async ledger connection issues on iOS

### PR DESCRIPTION
**Pull request by TheTreek**
Change `connectToPools` function to sequentially connect to pools. Previously there were [issues on iOS](https://github.com/hyperledger/aries-framework-javascript/issues/647) because of too many open sockets on this function.

### CODE REVIEW

**Comment by TimoGlastra** [comment]
How is this PR related to https://github.com/hyperledger/aries-framework-javascript/pull/804? Should we add a note to this code explaining why we're doing it in sequence instead of in parallel? Or is this change unrelated to that change?

**Comment by TimoGlastra** [comment]
Will this also fix the issue with `connectToIndyLedgersOnStartup`?

**Comment by TheTreek** [comment]
> How is this PR related to #804? Should we add a note to this code explaining why we're doing it in sequence instead of in parallel? Or is this change unrelated to that change?

The issue we were having is we tried to connect to all ledgers in parallel. This would cause us to  reach the resource limit very quickly, so instead of doing it in parallel we do it in sequence so we don't use too many resources.

> Will this also fix the issue with `connectToIndyLedgersOnStartup`?

Yes, this is the main goal of this PR.

**Comment by TimoGlastra** [comment]
> The issue we were having is we tried to connect to all ledgers in parallel. This would cause us to reach the resource limit very quickly, so instead of doing it in parallel we do it in sequence so we don't use too many resources

Can we add a comment to the relevant code explaining this? I'm worried this will get lost and 'fixed' to parallel opening of pools in the future again.

**Comment by TimoGlastra** [comment]
> Yes, this is the main goal of this PR

That is really great to hear!

**Comment by TheTreek** [comment]
> > The issue we were having is we tried to connect to all ledgers in parallel. This would cause us to reach the resource limit very quickly, so instead of doing it in parallel we do it in sequence so we don't use too many resources
> 
> Can we add a comment to the relevant code explaining this? I'm worried this will get lost and 'fixed' to parallel opening of pools in the future again.

Done!

**Comment by TimoGlastra** [comment]
Thansk @TheTreek, if you can update your branch I can merge!

**Review by TimoGlastra — APPROVED** [review]

**Comment by TimoGlastra** [comment]
Sorry it's out of date again :( Can you update again?

**Pull request merged**
