### PR TITLE
fix: date parsing

### PR DESCRIPTION
**Pull request by seajensen**
# Summary of Changes

Added transform function for parsing dates from multiple formats. Added transform function to basic messaging.

# Related Issues

N/A

# Pull Request Checklist

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this).
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components.
- [x] Added **tests** for changed code (run `scripts/preflight` to run tests and check code style).
- [x] Prefixed code comments with GitHub nick and an appropriate prefix.
- [x] Coding style is consistent with the rest of the framework.
- [x] Updated **documentation** for changed code and new or modified features.

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Comment by TimoGlastra** [comment]
@seajensen What format is not working with the JS date? Basic message uses ISO8601, which I think JS supports

**Comment by seajensen** [comment]
> @seajensen What format is not working with the JS date? Basic message uses ISO8601, which I think JS supports

Apologies, I forgot to link the issue. This is in reference to https://github.com/hyperledger/aries-framework-javascript/issues/301. @JamesKEbert might be able to fill in some additional details.

**Comment by JamesKEbert** [comment]
Yes! I had meant to follow up on the issue. So, from my findings, ISO 8601 dates do not allow spaces in the name, but [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) that is an extension to ISO 8601 (as I currently understand it) would allow a space. You are correct that we can parse ISO 8601 strings in both React Native and Node (and I assume Electron), however what is being received from ACA-Py isn't strictly ISO 8601, which maybe is something I should raise on that side. 
Regardless, I was unable to find any polyfill for this unfortunately, and date issues are not exactly a rare occurrence. Using Luxon gives additional flexibility and assurance of parsing across different environments. Happy to hear your thoughts though!

**Comment by blu3beri** [comment]
ISO 3339 is indeed an extension of ISO 8601. Both ISO's specify that you are allowed to use another delimiter if any interacting party knows this ( quite odd IMO ). The Basic messaging RFC gives an example for an ISO 8601 date with a space as delimiter between date and time. 

My suggestion is for ACA-Py to change it and change it also in the RFC. However, since both RFCs technically allow it, I am not opposed to this fix. 

We could also write a parser that splits on `space` and joins on `T`, but I do not know enough about the ISO specifications to know if that will never fail.

**Review by JamesKEbert — CHANGES_REQUESTED** [review]

**Review by JamesKEbert — APPROVED** [review]
LGTM

**Review by TimoGlastra — APPROVED** [review]

**Comment by TimoGlastra** [comment]
> Yes! I had meant to follow up on the issue. So, from my findings, ISO 8601 dates do not allow spaces in the name, but [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) that is an extension to ISO 8601 (as I currently understand it) would allow a space. You are correct that we can parse ISO 8601 strings in both React Native and Node (and I assume Electron), however what is being received from ACA-Py isn't strictly ISO 8601, which maybe is something I should raise on that side.
> Regardless, I was unable to find any polyfill for this unfortunately, and date issues are not exactly a rare occurrence. Using Luxon gives additional flexibility and assurance of parsing across different environments. Happy to hear your thoughts though!

@JamesKEbert As I understand it from this thread, ACA-Py _does_ send ISO 8601.

https://chat.hyperledger.org/group/os2iqWFM5k2usnrEP?msg=RR5mMYJdxFcYFBLMQ

And after doing a bit more research, it seems that JS `Date` only supports a simplified version of ISO8601. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#parameters

So ACA-Py is not necessarily the issue here, which makes this PR more an appropriate fix imo. 

Is basic message the only date that should be in ISO8601 format? No other properties/messages?

**Comment by swcurran** [comment]
Not quite, Timo.  ACA-Py does send ISO860, but is not sending timezone because the default call in Python doesn't send it.   So, yes, we are going to fix ACA-Py to include the timezone.  However, all recipients of W3C proofs have to handle cases with and without timezones.

**Comment by JamesKEbert** [comment]
@TimoGlastra it's worth noting @blu3beri's thoughts above:

> ISO 3339 is indeed an extension of ISO 8601. Both ISO's specify that you are allowed to use another delimiter if ALL interacting parties know this ( quite odd IMO ).
> 
> The Basic messaging RFC also gives an example for an ISO 8601 date with a space as delimiter between date and time.
> 
> My suggestion is for ACA-Py to change it and change it also in the RFC. However, since both RFCs technically allow it, I am not opposed to this fix.

I'd recommend the Aries RFC changing to not include the space for additional clarity--however, you are correct that this is technically feasible under ISO 8601 according to Berend's findings, since it's defined in the Aries basic messaging RFC. I am not actually immediately sure on other date fields in Aries (I hadn't gotten to it), but I can look into it.

**Comment by JamesKEbert** [comment]
Ahh I just identified/realized in [RFC 74 DIDComm Best Practices](https://github.com/hyperledger/aries-rfcs/blob/08653f21a489bf4717b54e4d7fd2d0bdfe6b4d1a/concepts/0074-didcomm-best-practices/README.md#_time) that the use of a space instead of "T" is allowed and called out as supported behavior.

**Pull request merged**
