### PR TITLE
mediation clean up

### PR DESCRIPTION
**Pull request by burdettadam**
this PR contains code merged from main with fixes to demonstrate mediation with WebSocket transports.

### CODE REVIEW

**Comment by genaris** [comment]
@burdettadam very nice work on the e2e test! I think this will allow to finally remove the dependency on running separate scripts for mediators.

I hope everything works fine when merging with the latest changes I introduced at mediation-rebased branch. I've fixed a few bugs I had on my side regarding the `promiseWithTimeout` and `KeylistUpdated` event (not sure if it's the best way to fix them, as I feel that internal routing event naming is not clear enough).

For the rest of the changes (such as the `autoAcceptMediationRequests` flag and cleaning up of mediation-client and other classes) I don't think there will be any issue.

**Comment by burdettadam** [comment]
@genaris, Thanks. I did fix some small things when I cherry-picked your contributions, I think also needed to change something for the `keylistUpdated` flow. Is there more code I can cherry-pick? I am open to suggestions if you see improvements I overlooked. 
I think we will be able to condense a lot of code as things become more stable with mediation. @JamesKEbert was able to fix some frustrating issues I had with mocking transports, things are much better now in e2e.  
I do realize there is some funny naming, suggestions are welcome. :)

**Comment by genaris** [comment]
@burdettadam, yeah your cherry-pick with fixes was almost perfect! After your PR including it, I committed some minor fixes (you can check it [here](https://github.com/hyperledger/aries-framework-javascript/commit/8de0bbaed4864bd9fb6b871a55fff4a1a0838171)). It seems that this PR can be merged without any major problem.

The only conflicting point could be the `KeyListUpdated` routing event type I added to distinguish the one generated in mediator service for sending the key list update response (`MediationKeylistUpdated`) from the one generated for updating keys in a mediation record (used in both mediator and recipient modules). I was a bit lost out there (though I managed to make it work fine in the flow I implemented in [e2e.http.test.ts](https://raw.githubusercontent.com/hyperledger/aries-framework-javascript/8de0bbaed4864bd9fb6b871a55fff4a1a0838171/samples/__tests__/e2e.http.test.ts)). I'm sure that naming can be improved!

**Comment by TimoGlastra** [comment]
@burdettadam quite some changes in the main branch. Let me know if I can help with merging / rebasing

**Pull request closed without merging**
