### PR TITLE
docs: remove remaining docs

### PR DESCRIPTION
**Pull request by morrieinmaas**
TODO:
* update proofs docs for v0.0.3 update for anoncreds

Signed-off-by: Moriarty <moritz@animo.id>

### CODE REVIEW

**Comment by morrieinmaas** [comment]
closes #1072

**Comment by blu3beri** [comment]
Was the idea not to move all documentation to the new repository? It seems a bit weird to keep this file here.

**Comment by morrieinmaas** [comment]
> Was the idea not to move all documentation to the new repository? It seems a bit weird to keep this file here.

Added for completeness - also made a PR in the docs repo

**Comment by TimoGlastra** [comment]
As you already made a PR to the docs repo (which is great, thanks!), can you update this pr to remove the ledger documentation? We'll just use the docs site from now on then

**Review by TimoGlastra — APPROVED** [review]

**Pull request merged**
