### PR TITLE
fix: mediation record checks for pickup v2

### PR DESCRIPTION
**Pull request by TimoGlastra**
Adds checks in the mediation recipient service for mediation record state and role. Also splits up the sending of the status request message to be more in line with separation of service/module in the rest of the framework. 

Finally, this updates the processing of the message to be using the event emitter. We also use this approach for pickup v1 and it was causing issues in the oob branch due to circular dependencies.

### CODE REVIEW

**Comment by TimoGlastra** [comment]
@KolbyRKunz could you give this PR a look and see if the changes look good to you? Thanks!

**Review by KolbyRKunz — APPROVED** [review]
This all looks good to me, thank you for catching the `mediatorrecord.connectionId` issue in `sendStatusRequest`

**Review by TheTreek — APPROVED** [review]
This looks good.

**Review by blu3beri — APPROVED** [review]
Looks good :)

**Pull request merged**
