### PR TITLE
fix: create new socket if socket state is 'closing'

### PR DESCRIPTION
**Pull request by niall-shaw**
Found issue where sending message fails with `Socket is not open.` when only using websocket transports (no http transports).

WS is used to create initial connection, and then starts before mediation request, causing socket state to update to 'CLOSING'. Since this is done before the `close` event is emitted, the relevant socket map value  of `WsOutboundTransport` hasn't been deleted yet, so when we try to send the next message too quickly this error case can happen.

### CODE REVIEW

**Review by TimoGlastra — APPROVED** [review]

**Comment by genaris** [comment]
I think this is related to the problem found in #1025

**Comment by niall-shaw** [comment]
Any ideas why the test failed?

**Comment by swcurran** [comment]
@jleach — could this be related to the “first credential delay” issue?  

Does this manifest in delays or in errors?

**Comment by niall-shaw** [comment]
> Does this manifest in delays or in errors?

@swcurran in the use cases I was experimenting with, it always resulted in an error.

**Review by genaris — APPROVED** [review]
This is a very nice and elegant fix for this issue. 

I think in a near future we have to re-think a bit the way we handle WebSockets in inbound and outbound transporters, as IMHO one of the key purposes of them is to have avoid the need of re-opening and closing HTTP connections when there are several exchanges within a short time frame. So, even if a message does not have a return_route set, I think the socket should not be immediately closed but rather kept opened for some seconds (configurable if needed), so it can be re-used in case more messages are going to be sent.

**Comment by niall-shaw** [comment]
@genaris @TimoGlastra - do you know why the tests are now failing? It doesn't make any sense to me why this change would cause the tests to fail

**Comment by TimoGlastra** [comment]
The issues are not related to your PR. @genaris just made a PR to fix the CI issues, let's see if they pass now

**Pull request merged**
